config/routes.rb
Rails.application.routes.draw do
  devise_for :sellers, controllers: {
    sessions:      'sellers/sessions',
    passwords:     'sellers/passwords',
    registrations: 'sellers/registrations'
  }
  devise_for :buyers, controllers: {
    sessions:      'buyers/sessions',
    passwords:     'buyers/passwords',
    registrations: 'buyers/registrations'
  }
  root to: "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :explanation
    validates :category_id
    validates :days_delivery_id
    validates :price
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  private

    def basic_auth
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
      end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @item = Item.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<%= render "shared/header"  %>

<div class='main'>
  <div class='title-contents'>
    産直食材の購入と農家のレシピ
  </div>
  <h2>出品者</h2>
  <%= link_to '新規登録', new_buyer_registration_path %>
</div>

<%= render "shared/footer"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MogumoguPark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    こだわり食材を簡単に購入可能
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
    <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='mogumogu-details'>
      <h2 class='footer-content-head'>MOGUMOGU PARKについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'MOGUMOGU PARK利用規約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='mogumogu-details'>
      <h2 class='footer-content-head'>商品を見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to '出品者一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='mogumogu-details'>
      <h2 class='footer-content-head'>MOGUMOGU PARKついて</h2>
      <ul>
        <li><%= link_to '利用ガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'ロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("icon_radish.png", class:"logo-white"), "#" %>
  <p>© MOGUMOGU PARK</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("icon_radish.png", class:"mogumogu-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
    </ul>

    <ul class='lists-right'>
        <li><%= link_to 'ログイン', new_buyer_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_buyer_registration_path, class: "sign-up" %></li>
    </ul>
  </div>
</header>